@extends('layouts.backend.app')

@push('css')
<!-- Date --> 
<link rel="stylesheet" href="{{ asset('asset/plugins/jquery-ui/jquery-ui.css')}}">
@endpush
<title>Create Sales Order</title>
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Create Sales Order</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item">Transaction</li>
                <li class="breadcrumb-item active">Sales</li>
            </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
        <!-- Horizontal Form -->
        <div class="card card-info">
            <div class="card-header">
            <h3 class="card-title"><i class="fas fa-paste"></i> Create Sales Order</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            
            <form class="form-horizontal" method = "POST" action = "{{ route('sales.store') }}">
            @csrf
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group row">
                    <div class="col-md-12">
                        <div class="alert alert-info alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h5><i class="icon fas fa-info" d></i> Info!</h5>
                            A sales order is a document generated by the seller upon receiving a 
                            purchase order from a <strong>buyer/customer</strong> specifying the details about the product or service 
                            along with price, quantity, buyer details.
                        </div>
                        <strong><font color="red">*</font> Indicates required fields.</strong>
                    </div>
                    <div class="col-md-4">
                        <label for="date" class="col-sm-6 col-form-label">Date <font color="red">*</font></label>
                        <div class="input-group mb-2 {{$errors->has('date') ? 'has-error' : ''}}" >
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                            </div>
                            <input type="text" 
                                    class="form-control" 
                                    id="date" 
                                    name = "date"
                                    autocomplete="off" 
                                    value="{{ old('date') }}"
                                    required>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="invoice_no" class="col-sm-6 col-form-label">Invoice No. <font color="red">*</font></label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend {{$errors->has('invoice_no') ? 'has-error' : ''}}">
                                <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                            </div>
                            <input type="text" 
                                    class="form-control" 
                                    id="invoice_no" 
                                    name = "invoice_no" 
                                    maxlength = "15"
                                    value="{{ $invoice_no }}"
                                    onkeyup="this.value=this.value.replace(/[^\d]/,'')" 
                                    required readonly>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="shop_name" class="col-sm-6 col-form-label">Customer Name <font color="red">*</font></label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend {{$errors->has('shop_name') ? 'has-error' : ''}}">
                                <span class="input-group-text"><i class="fas fa-user-check"></i></span>
                            </div>
                            <input type = "text" 
                                    class="form-control" 
                                    id="shop_name" 
                                    name = "shop_name" 
                                    placeholder = "Customer Name" 
                                    autocomplete = "on"
                                    value="{{ old('shop_name') }}"
                                    style="text-transform: uppercase"
                                    required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class = "form-group row">
                    <div class="col-md-12">
                        <label for = "info" class = "col-md-4 col-form-label"><strong><i class="fas fa-info-circle"></i></strong> Sales Order Information</label>
                        <div class = "col-sm-12  {{$errors->has('product_information') ? 'has-error' : ''}}">
                            <textarea name = "product_information" 
                                    class = "form-control" 
                                    rows = "4"
                                    value="{{ old('product_information') }}"
                                    style="text-transform: uppercase"
                                    ></textarea>
                        </div>
                    </div>
                </div>

                <div class = "col-md-12 field-wrapper">
                    <div class = "form-group row">
                        <div class="col-md-12">
                            <label for="id_raw_product" class="col-sm-4 col-form-label">Product Name <font color="red">*</font></label>
                        </div>
                        <div class="col-sm-3">
                            <input type="hidden" 
                                    readonly = "true" 
                                    class="form-control" 
                                    id="id_raw_product_1" 
                                    name = "id_raw_product[]" 
                                    placeholder = "Product Name" 
                                    required>

                            <input type="text" 
                                    readonly = "true" 
                                    class="form-control" 
                                    id="name_raw_product_1" 
                                    name = "name_raw_product[]" 
                                    value="{{ old('id_raw_product_1') }}"
                                    placeholder = "Product Name"
                                    required>
                        </div>
                        <div class="col-sm-2">
                            <a href = "/transaction/sales/product/popup_media/1" 
                                class = "btn btn-info" 
                                title = "Product" 
                                data-toggle = "modal" 
                                data-target = "#modal-default">Product</a>
                        </div>
                        <div class="col-sm-3">
                            <input type="number" 
                                class="form-control" 
                                id="price_1" 
                                name = "price[]" 
                                value="{{ old('price_1') }}"
                                placeholder = "Price" 
                                onkeyup="this.value=this.value.replace(/[^\d]/,'')" required>
                        </div>
                        <div class="col-sm-2">
                            <input type="number" 
                                class="form-control" 
                                id="total_1" 
                                name = "total[]" 
                                value="{{ old('total_1') }}"
                                placeholder = "Quantity" 
                                onkeyup="this.value=this.value.replace(/[^\d]/,'')" required>
                        </div>
                        <div class = "col-sm-2">
                            <a href = "javascript:void(0)" class = "btn btn-primary add_Button" title = "Add Row"><i class = "fas fa-plus"></i></a>

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-default float-right" name = "submit_create" id = "submit_create">Submit</button>
            </div>
            <!-- /.card-footer -->
            </form>
        </div>
        <!-- /.card -->

        </div>
        <!--/.col (left) -->
        <!-- right column -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    
</section>
<!-- /.content -->

{{--    Modal --}}  
<div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h4 class="modal-title"><i class="fas fa-boxes"></i> Products List</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"</span>
                </button>
            </div>
            <div class="modal-body">
                
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@endsection

@push('js')
<script>   
    $("#submit_create").prop('disabled', true);

    $(document).ready(function(){
        var addButton = $('.add_Button');
        var wrapper = $('.field-wrapper');
        var X = "{{ $detail_count + 1}}";

        var inputQtyLength = $('[id^=total_]').length;

        $(addButton).click(function(){
            X++;
            $(wrapper).append(' <div class = "form-group row"> ' +
                    '<div class="col-sm-3">' +
                        '<input type="hidden" readonly = "true" class="form-control" id="id_raw_product_'+X+'" name = "id_raw_product[]" placeholder = "Product Name" value = {{ old("id_raw_product_'+X+'") }} required>' +
                        '<input type="text" readonly = "true" class="form-control" id="name_raw_product_'+X+'" name = "name_raw_product[]" placeholder = "Product Name"  value = {{ old("name_raw_product_'+X+'") }}>'+
                    '</div>' +
                    '<div class="col-sm-2">' +
                        '<a href = "/transaction/sales/product/popup_media/'+X+'" class = "btn btn-info" title = "Product" data-toggle = "modal" data-target = "#modal-default">Product</a>' +
                    '</div>' +
                    '<div class="col-sm-3">' +
                        '<input type="text" class="form-control" id="price_'+X+'" value="{{ old("price_'+X+'") }}" name = "price[]" placeholder = "Price" required>' +
                    '</div>' +
                    '<div class="col-sm-2">' +
                        '<input type="text" class="form-control" id="total_'+X+'" value="{{ old("total_'+X+'") }}" name = "total[]" placeholder = "Quantity" required>' +
                    '</div>' +
                    '<div class = "col-sm-2">' +
                        '<a href = "javascript:void(0)" class = "btn btn-danger remove" title = "Delete"><i class = "fas fa-minus"></i></a>' +
                    '</div>' +
                '</div>'
            );
        });

        $(wrapper).on('click', '.remove', function(e){
            if(confirm("Do you want to delete this row?")){
                e.preventDefault();
                $(this).parent().parent().remove();
            }
        });

        $("#date").datepicker('setDate', new Date());
    });

    $('#date').datepicker({
        autoclone:true,
        dateFormat:'dd-mm-yy',
    });

    $("#date").datepicker({
        onSelect: function(dateText) {
        var currentDateInput = $(this).val();
    }}).on("change", function() {

        currentDate = this.value;
       
        if (!moment(currentDate, 'DD-MM-YYYY', true).isValid()){         
            $(this).val('');      
            alert("Not a valid date! Date must be in 'DD-MM-YYYY' format. Choose from date picker by clicking the Date field.");
        }
    });

    $('#modal-default').bind('show.bs.modal', function(e){
        var link = $(e.relatedTarget);
        $(this).find(".modal-body").load(link.attr("href"));
    });

    $("input[id^='name_raw_product_'], input[id^='total']").on("keyup", function(){
        if($(this).val() != ""){
            $("#submit_create").prop('disabled', false);
        } else {
            $("#submit_create").prop('disabled', true);
        }
    });

</script>
@endpush